networks:
  fastapi-net:
    external: true

services:
  fastapi:
    image: ${DOCKERHUB_USERNAME}/fastapi:${IMAGE_TAG:-latest}
    container_name: fastapi-container
    restart: always
    ports:
      - "8000:80"
    networks:
      - fastapi-net
