networks:
  dev-ops-assignment-api:
    driver: bridge
    name: dev-ops-assignment-api

services:
  fastapi:
    image: tzionasev/fastapi:${IMAGE_TAG:-latest}
    container_name: fastapi-container
    restart: always
    ports:
      - "8000:80"
    networks:
      - dev-ops-assignment-api
