networks:
  dev-ops-assignment-api:
      external: true

services:
  fastapi:
    # Image will be built as soon as it is pushed to the repo
    image: tzionasev/fastapi:${IMAGE_TAG:-latest}
    container_name: fastapi-container
    restart: always
    ports:
      - "8000:80"
    networks:
      - dev-ops-assignment-api
