name: Dev-ops-assignnment-api-pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: test, build & push image to docker hub
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: main
    # Step 2: Set up Python 3.x (for testing before Docker build)
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    # Step 3: Install dependencies and run tests using Pytest
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run tests with Pytest
      run: |
        pytest
        
    # Step 4: Set up Docker Buildx
    - name: setup docker buildx
      uses: docker/setup-buildx-action@v2
      
    # Step 5: Log in to Docker Hub (or GitHub Container Registry)
    - name: docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    # Step 6: Build and push Docker image
    - name: build and push api
      id: build-push-api
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/fastapi:latest

    # Step 7: SSH into the Azure VM and deploy Docker container in ssh -i use your own path/to/key.pem
    - name: Deploy to Azure VM
      run: |
        echo "${{ secrets.AZURE_SSH_KEY }}" > /tmp/key.pem
        cat /tmp/key.pem
        chmod 600 /tmp/key.pem
        ssh -i /tmp/key.pem ${{ secrets.AZURE_USERNAME }}@${{ secrets.AZURE_VM_IP }} << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/fastapi:latest
          docker stop fastapi-container || true
          docker rm fastapi-container || true
          docker run -d -p 8000:8000 --name fastapi-container ${{ secrets.DOCKER_USERNAME }}/fastapi:latest
        EOF
      # env:
      #   DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #   DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #   AZURE_VM_IP: ${{ secrets.AZURE_VM_IP }}
